[package]
name = "delegation-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dependencies.delegation-mock]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.4"
