[package]
name = "liquid-staking-interactor"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[[bin]]
name = "liquid-staking-interactor"
path = "src/liquid_staking_interactor_main.rs"

[lib]
path = "src/liquid_staking_interactor.rs"

[dependencies.liquid-staking]
path = ".."

[dependencies.dharitri-sc-snippets]
version = "0.54.4"

[dependencies.dharitri-sc]
version = "0.54.4"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

[features]
chain-simulator-tests = []
