[package]
name = "delegation-mock"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[lib]
path = "src/delegation.rs"

[dependencies.dharitri-sc]
version = "0.54.4"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.4"
