// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    delegation_mock
    (
        init => init
        depositREWA => deposit_rewa
        delegate => delegate
        unDelegate => undelegate
        withdraw => withdraw
        claimRewards => claim_rewards
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
